# Calculate and Compare Agreement/Reliability by Gender

In [2]:
import pandas as pd

In [7]:
from sklearn.metrics import cohen_kappa_score
import krippendorff

## 1. Read Female and Male Datasets

In [5]:
df_female_test = pd.read_csv("df_female_test.csv")
df_female_test

,tweet_id_comment_nr,text,majority_vote_respect,majority_vote_attack,majority_vote_argument,text_cleaned_01,text_cleaned_02
0,316_7,"@USER @USER Over 6 jaar 1,5⁰, zó heftig? Dan z...",1.0,0.0,1.0,"Over 6 jaar 1,5⁰, zó heftig? Dan zijn we sowie...","Over 6 jaar 1,5⁰, zó heftig? Dan zijn we sowie..."
1,479_1,@USER Dat punt van die klimaatverandering is n...,1.0,0.0,0.0,Dat punt van die klimaatverandering is nu wel ...,Dat punt van die klimaatverandering is nu wel ...
2,151_1,@USER Ik voel een nieuw podcast opkomen: “Mijn...,1.0,0.0,0.0,Ik voel een nieuw podcast opkomen: “Mijn kappe...,Ik voel een nieuw podcast opkomen: “Mijn kappe...
3,311_3,@USER Zaterdagochtend 12-2-22. Blauwe lucht. V...,1.0,0.0,1.0,Zaterdagochtend 12-2-22. Blauwe lucht. Vliegtu...,Zaterdagochtend 12-2-22. Blauwe lucht. Vliegtu...
4,513_7,@USER @USER klimaatontkenner=#misinformatie ht...,0.0,0.0,0.0,klimaatontkenner=#misinformatie https://t.co/I...,klimaatontkenner=#misinformatie
...,...,...,...,...,...,...,...
385,249_4,"@USER Muah, ik weet niet of dat zo is. Ik heb ...",1.0,0.0,1.0,"Muah, ik weet niet of dat zo is. Ik heb veel s...","Muah, ik weet niet of dat zo is. Ik heb veel s..."
386,550_4,"@USER @USER @USER Utopisme en activisme, daare...",1.0,0.0,0.0,"Utopisme en activisme, daarentegen, lijken voo...","Utopisme en activisme, daarentegen, lijken voo..."
387,524_5,@USER Beter ten halve gekeerd hoor…🤔😀,1.0,0.0,1.0,Beter ten halve gekeerd hoor…🤔😀,Beter ten halve gekeerd hoor…🤔😀
388,568_8,@USER @USER @USER In alle grote kranten wordt ...,1.0,1.0,1.0,In alle grote kranten wordt klimaatverandering...,In alle grote kranten wordt klimaatverandering...
389,204_1,@USER @USER Hier heb je ruim 31 duizend rockst...,0.0,0.0,0.0,Hier heb je ruim 31 duizend rocksterren:\nhttp...,Hier heb je ruim 31 duizend rocksterren:\n\nHo...

In [6]:
df_male_test = pd.read_csv("df_male_test.csv")
df_male_test

,tweet_id_comment_nr,text,majority_vote_respect,majority_vote_attack,majority_vote_argument,text_cleaned_01,text_cleaned_02
0,316_7,"@USER @USER Over 6 jaar 1,5⁰, zó heftig? Dan z...",1.0,0.0,0.0,"Over 6 jaar 1,5⁰, zó heftig? Dan zijn we sowie...","Over 6 jaar 1,5⁰, zó heftig? Dan zijn we sowie..."
1,479_1,@USER Dat punt van die klimaatverandering is n...,1.0,0.0,0.0,Dat punt van die klimaatverandering is nu wel ...,Dat punt van die klimaatverandering is nu wel ...
2,151_1,@USER Ik voel een nieuw podcast opkomen: “Mijn...,1.0,0.0,0.0,Ik voel een nieuw podcast opkomen: “Mijn kappe...,Ik voel een nieuw podcast opkomen: “Mijn kappe...
3,311_3,@USER Zaterdagochtend 12-2-22. Blauwe lucht. V...,1.0,0.0,0.0,Zaterdagochtend 12-2-22. Blauwe lucht. Vliegtu...,Zaterdagochtend 12-2-22. Blauwe lucht. Vliegtu...
4,513_7,@USER @USER klimaatontkenner=#misinformatie ht...,0.0,1.0,1.0,klimaatontkenner=#misinformatie https://t.co/I...,klimaatontkenner=#misinformatie
...,...,...,...,...,...,...,...
385,249_4,"@USER Muah, ik weet niet of dat zo is. Ik heb ...",1.0,0.0,0.0,"Muah, ik weet niet of dat zo is. Ik heb veel s...","Muah, ik weet niet of dat zo is. Ik heb veel s..."
386,550_4,"@USER @USER @USER Utopisme en activisme, daare...",1.0,0.0,0.0,"Utopisme en activisme, daarentegen, lijken voo...","Utopisme en activisme, daarentegen, lijken voo..."
387,524_5,@USER Beter ten halve gekeerd hoor…🤔😀,1.0,0.0,0.0,Beter ten halve gekeerd hoor…🤔😀,Beter ten halve gekeerd hoor…🤔😀
388,568_8,@USER @USER @USER In alle grote kranten wordt ...,0.0,0.0,0.0,In alle grote kranten wordt klimaatverandering...,In alle grote kranten wordt klimaatverandering...
389,204_1,@USER @USER Hier heb je ruim 31 duizend rockst...,1.0,1.0,1.0,Hier heb je ruim 31 duizend rocksterren:\nhttp...,Hier heb je ruim 31 duizend rocksterren:\n\nHo...

## 2. Calculate Intercoder Agreement

### 2.1 Personal Attack

In [14]:
# Calculate Cohen's Kappa
kappa = cohen_kappa_score(df_male_test['majority_vote_attack'], df_female_test['majority_vote_attack'])

print(f"Cohen's Kappa Score: {kappa}")

Cohen's Kappa Score: 0.5282423477437678

In [15]:
data_matrix = df_male_test['majority_vote_attack'],df_female_test['majority_vote_attack'].to_numpy().T  # Transposing to get "item-by-coder" matrix format

# Calculate Krippendorff's alpha for nominal data
alpha_nominal = krippendorff.alpha(reliability_data=data_matrix, level_of_measurement="nominal")

print(f"Krippendorff's Alpha (Nominal): {alpha_nominal}")

Krippendorff's Alpha (Nominal): 0.528809993425378

### 2.2 Respect

In [16]:
# Calculate Cohen's Kappa
kappa = cohen_kappa_score(df_male_test['majority_vote_respect'], df_female_test['majority_vote_respect'])

print(f"Cohen's Kappa Score: {kappa}")

Cohen's Kappa Score: 0.48034643570952695

In [17]:
data_matrix = df_male_test['majority_vote_respect'],df_female_test['majority_vote_respect'].to_numpy().T  # Transposing to get "item-by-coder" matrix format

# Calculate Krippendorff's alpha for nominal data
alpha_nominal = krippendorff.alpha(reliability_data=data_matrix, level_of_measurement="nominal")

print(f"Krippendorff's Alpha (Nominal): {alpha_nominal}")

Krippendorff's Alpha (Nominal): 0.4802794238844629

### 2.3 Substantial Argument

In [18]:
# Calculate Cohen's Kappa
kappa = cohen_kappa_score(df_male_test['majority_vote_argument'], df_female_test['majority_vote_argument'])

print(f"Cohen's Kappa Score: {kappa}")

Cohen's Kappa Score: -0.24364252845725343

In [19]:
data_matrix = df_male_test['majority_vote_argument'],df_female_test['majority_vote_argument'].to_numpy().T  # Transposing to get "item-by-coder" matrix format

# Calculate Krippendorff's alpha for nominal data
alpha_nominal = krippendorff.alpha(reliability_data=data_matrix, level_of_measurement="nominal")

print(f"Krippendorff's Alpha (Nominal): {alpha_nominal}")

Krippendorff's Alpha (Nominal): -0.3086868686868687

## 3. Distribution of Disagreement tbc

In [25]:
# here we would need the data sets where every row is an annotator

In [27]:
# read annotations
df_coders = pd.read_csv('../data/annotations/twitter_klimaat_discussie_coderingen.csv')
df_coders

,coder,jobset,scientific_consensus.pro_klimaat,scientific_consensus.belangrijk_onderwerp,scientific_consensus.sterke_mening,scientific_consensus.interesse_klimaat,age,gender,education,workhours,tweet_id,tweet_pro_klimaat,comment_nr,comment_pro_klimaat,comment_inhoudelijk_argument,comment_persoonlijke_aanval,comment_over_communicatie,comment_respectvol,id
0,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,Voorbereidend of kort middelbaar beroepsonderw...,Tussen de 10 en 20 uur,22,Ja,1,Ja,Inhoudelijk argument,Persoonlijke aanval,Oneens,Oneens,11_22_1
1,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,Voorbereidend of kort middelbaar beroepsonderw...,Tussen de 10 en 20 uur,22,Ja,2,Ja,Inhoudelijk argument,Persoonlijke aanval,Eens,Oneens,11_22_2
2,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,Voorbereidend of kort middelbaar beroepsonderw...,Tussen de 10 en 20 uur,22,Ja,3,Ja,Geen inhoudelijk argument,Geen persoonlijke aanval,Eens,Oneens,11_22_3
3,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,Voorbereidend of kort middelbaar beroepsonderw...,Tussen de 10 en 20 uur,22,Ja,4,Neutraal,Inhoudelijk argument,Persoonlijke aanval,Eens,Eens,11_22_4
4,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,Voorbereidend of kort middelbaar beroepsonderw...,Tussen de 10 en 20 uur,22,Ja,5,Neutraal,Inhoudelijk argument,Geen persoonlijke aanval,Oneens,Eens,11_22_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42839,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",Tussen de 30 en 40 uur,378,Ja,1,Nee,Geen inhoudelijk argument,Geen persoonlijke aanval,Oneens,Oneens,2588_378_1
42840,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",Tussen de 30 en 40 uur,378,Ja,2,Nee,Geen inhoudelijk argument,Geen persoonlijke aanval,Oneens,Oneens,2588_378_2
42841,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",Tussen de 30 en 40 uur,378,Ja,3,Nee,Geen inhoudelijk argument,Geen persoonlijke aanval,Oneens,Oneens,2588_378_3
42842,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",Tussen de 30 en 40 uur,378,Ja,4,Nee,Geen inhoudelijk argument,Geen persoonlijke aanval,Oneens,Oneens,2588_378_4
42843,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",Tussen de 30 en 40 uur,378,Ja,5,Nee,Geen inhoudelijk argument,Persoonlijke aanval,Oneens,Eens,2588_378_5

In [34]:
df_female_coders = pd.read_csv("df_female_coders.csv")
df_female_coders

,id,tweet_id_comment_nr,text,coder,gender,comment_pro_klimaat,comment_respectvol_binary,comment_inhoudelijk_argument_binary,comment_persoonlijke_aanval_binary
0,11_22_1,22_1,@USER Men riep hier jaren te schreeuwen over '...,11,Vrouw,Ja,0,1,1
1,11_22_2,22_2,"@USER Je wou zeggen ""Is het een koude dag, het...",11,Vrouw,Ja,0,1,1
2,11_22_3,22_3,@USER Hij praat trouwens onzin want ik heb hie...,11,Vrouw,Ja,0,0,0
3,11_22_4,22_4,@USER Er zijn ongetwijfeld ook mensen met stad...,11,Vrouw,Neutraal,1,1,1
4,11_22_5,22_5,"@USER Nu woon ik ver van grote steden af, niet...",11,Vrouw,Neutraal,1,1,0
...,...,...,...,...,...,...,...,...,...
22208,2588_378_1,378_1,@USER Hoezo zelf gemaakt,2588,Vrouw,Nee,0,0,0
22209,2588_378_2,378_2,@USER Zijn neefje!!,2588,Vrouw,Nee,0,0,0
22210,2588_378_3,378_3,"@USER Netjes roch, slim ventje",2588,Vrouw,Nee,0,0,0
22211,2588_378_4,378_4,@USER Op zijn kop helaas,2588,Vrouw,Nee,0,0,0
22212,2588_378_5,378_5,"@USER Goed kijken, deuger",2588,Vrouw,Nee,1,0,1

In [35]:
len(df_female_coders.coder.unique()) # Nr of Coders

783

In [37]:
len(df_female_coders.tweet_id_comment_nr.unique()) # Nr of Tweets/Annos possible

2004

In [ ]:
#tbc